language: python
python:
  - "3.5"

services:
  - docker

install:
  - docker build -t simple-flask-app:latest .
  - docker run -d -p 5000:5000 simple-flask-app

before_script:
  - pip install -r requirements.txt
  
script:
  - docker ps | grep -q blog
